language: node_js
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#- npm install
- echo {\"token\":\"$TSDRC_TOKEN\"} > .tsdrc
- tsd reinstall --save --overwrite
before_install:
- export CHROME_BIN=chromium-browser
- npm install -g bower tsd tslint karma gulp jshint
cache:
  bundler: true
  directories:
  - node_modules
compiler:
- g++
- gcc
- clang
env:
  global:
  - CC=gcc-4.8
  - CXX=g++-4.8
  - secure: G8NSqBVJVX4mLrsWKDZh9eUMhlQrs/9z+9gAu8YC7mQ8ed0BlY4idrNI5vaD/+LsKSxEqhYO7U08Tn3KrtSo1sr7sSI47F1g/F8VCMXQW2eC89BiZh+9Td1qETvsW/jTFpF5QaQJBf5d6WBlpVp98KQOlLvUIL+Kyl08hhRmk/k=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
