language: node_js
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- echo {\"token\":\"$TSDRC_TOKEN\"} > .tsdrc
- typings install
before_install:
- rm npm-shrinkwrap.json
- export CHROME_BIN=chromium-browser
- npm install -g bower typings tslint gulp
cache:
  bundler: true
  directories:
  - node_modules
  - $(npm config get prefix)/bin/bower
  - $(npm config get prefix)/bin/typings
  - $(npm config get prefix)/bin/tslint
  - $(npm config get prefix)/bin/gulp
env:
  global:
  - CXX=g++-4.8
  - secure: G8NSqBVJVX4mLrsWKDZh9eUMhlQrs/9z+9gAu8YC7mQ8ed0BlY4idrNI5vaD/+LsKSxEqhYO7U08Tn3KrtSo1sr7sSI47F1g/F8VCMXQW2eC89BiZh+9Td1qETvsW/jTFpF5QaQJBf5d6WBlpVp98KQOlLvUIL+Kyl08hhRmk/k=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
